[package]
name = "ipc_tcp"
version = "0.1.0"
edition = "2021"



[dependencies]
#zmq =  "0.9.2" 
num_cpus = "1.0"
zeromq = "*"
string_template = "0.2.1"
tokio = { version = "1", features = ["full"] }

[features]
#vendored-zmq = ['zmq/vendored']

